@hostname = localhost

@port = 5000

@url = http://{{hostname}}:{{port}}/api

@persons = {{url}}/Persons

@booking = {{url}}/Bookings

#####################################
GET {{persons}} HTTP/1.1
###
GET {{persons}}/1 HTTP/1.1
###
POST {{persons}} HTTP/1.1
Content-Type: application/json

{
    "Firstname" : "Paul",
    "Lastname" : "Wiesinger",
    "Age" : 18
}
###
DELETE {{persons}}/5 HTTP/1.1
###
PUT {{persons}}/1 HTTP/1.1
Content-Type: application/json

{
    "Firstname" : "Edited",
    "Lastname" : "Edited",
    "Age" : 20
}
###
GET {{booking}} HTTP/1.1
###
GET {{booking}}/4 HTTP/1.1
###
