/**
 * WepApi Tennis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Booking } from './booking';


export interface Person { 
    id?: number;
    firstname?: string | null;
    lastname?: string | null;
    age?: number;
    bookings?: Array<Booking> | null;
}

